### ISSUE TITLE
collecting ... Segmentation fault

### ISSUE THREAD

**Issue by ChenhongyiYang** [StanfordVL/iGibson#1]
Hi, 

I installed the GibsonV2 following the installation tutorial, and there is not problem during installation, but I cannot run the pytest or the examples in the example folder:

platform linux -- Python 3.6.8, pytest-4.3.1, py-1.8.0, pluggy-0.9.0
rootdir: /scratch2/gibsonV2/GibsonEnvV2, inifile:
plugins: remotedata-0.3.1, openfiles-0.3.2, doctestplus-0.3.0, arraydiff-0.3
collecting ... Segmentation fault

how can I fix this?
Thanks

**Comment by fxia22** [comment]
can you try installing nvidia OpenGL drivers and make them visible?
`export LD_LIBRARY_PATH=/usr/lib/nvidia-<vvv>:$LD_LIBRARY_PATH`

**Comment by GELIELEO** [comment]
> Hi,
> 
> I installed the GibsonV2 following the installation tutorial, and there is not problem during installation, but I cannot run the pytest or the examples in the example folder:
> 
> platform linux -- Python 3.6.8, pytest-4.3.1, py-1.8.0, pluggy-0.9.0
> rootdir: /scratch2/gibsonV2/GibsonEnvV2, inifile:
> plugins: remotedata-0.3.1, openfiles-0.3.2, doctestplus-0.3.0, arraydiff-0.3
> collecting ... Segmentation fault
> 
> how can I fix this?
> Thanks
Hi, Have you solve your problem? please can you share some experience

**Comment by GELIELEO** [comment]
Hi, Have you solve your problem? please can you share some experience

**Comment by GELIELEO** [comment]
@ChenhongyiYang Hi, I meet the same problem as yours. Have you solve your problem? please can you share some experience?

**Comment by ArbiterGe** [comment]
Me too，I don‘t install OpenGL drivers and Segmentation fault (core dumped)

**Comment by roberto-martinmartin** [comment]
If you have this problem, please, try our latest version. It should solve the issue. If you are still encountering it, reopen the issue. Thanks!
