### ISSUE TITLE
should_open_all_doors not passed to BEHAVIOR scene initialization

### ISSUE THREAD

**Issue by kylehkhsu** [StanfordVL/iGibson#105]
In example config files for BEHAVIOR, the `should_open_all_doors` flag is used (e.g. [here](https://github.com/StanfordVL/iGibson/blob/ig-develop/igibson/examples/configs/behavior_onboard_sensing.yaml#L7)), presumably to specify that a scene's doors should be initialized to be open on episode reset. However, it seems that this is never passed to the scene initialization code in `iGBEHAVIORActivityInstance.initialize()`: `scene_kwargs` does not contain this key
```
    def load_behavior_task_setup(self):
        """
        Load task setup
        """
        # task
        task = self.config["task"]
        task_id = self.config["task_id"]
        scene_id = self.config["scene_id"]
        clutter = self.config["clutter"]
        online_sampling = self.config["online_sampling"]
        if online_sampling:
            scene_kwargs = {}
        else:
            scene_kwargs = {
                "urdf_file": "{}_task_{}_{}_{}_fixed_furniture".format(scene_id, task, task_id, self.instance_id),
            }
        bddl.set_backend("iGibson")
        self.task = iGBEHAVIORActivityInstance(task, task_id)
        self.task.initialize_simulator(
            simulator=self.simulator,
            scene_id=scene_id,
            load_clutter=clutter,
            scene_kwargs=scene_kwargs,
            online_sampling=online_sampling,
        )
```

Is this intentional?

**Comment by ChengshuLi** [comment]
Hi Kyle, you are right that `should_open_all_doors: true` is not used anymore. We will remove them from the config files for BEHAVIOR. Thank you for reporting this.
