### ISSUE TITLE
How can I interact with the objects in the simulation environment?

### ISSUE THREAD

**Issue by chenguanqi** [StanfordVL/iGibson#107]
Hi, 
When running the provided demo _mouse_interaction.py_, I can only move in the simulation environment and can't interact with objects. How can I interact with the objects in the simulation environment?

**Comment by fxia22** [comment]
Hi @chenguanqi, you can press m to change the mode from navigation to interaction and then be able to interact with objects in the scene. A full guide can be found here: http://svl.stanford.edu/igibson/docs/viewer.html

**Comment by chenguanqi** [comment]
Thank you! My problem is solved.
