### ISSUE TITLE
3d2d standford dataset annotations

### ISSUE THREAD

**Issue by elhamAm** [StanfordVL/iGibson#112]
When using the 3d2d standford dataset  in igibson, the segmentation of the categories is not possible. It would be maybe possible to add the categories manually to the mesh_up_z.obj but even then in the gibson_indoor_scene.py, no category function is implemented. Is this something that is being worked on? If not, do you have any guidance? Thank you in advance.

**Comment by elhamAm** [comment]
Figured it out !

**Comment by eunsunlee** [comment]
@elhamAm Hi,  I was wondering if you could share how you implemented the category function!

**Comment by elhamAm** [comment]
Hi I added you as a collaborator :) you should have an invite

**Comment by Atellas23** [comment]
Hey @elhamAm, would it be possible for you to share how did you manage to run iGibson with the 3D2D dataset and render the semantic segmentation?

**Comment by elhamAm** [comment]
Hey I did this a long time ago, so I don't know but I shared the repo I made so if the answer is there, it's there :)
