### ISSUE TITLE
3 iGibson tests are broken

### ISSUE THREAD

**Issue by jaraujo98** [StanfordVL/iGibson#113]
I recently installed iGibson on Ubuntu 20.04. Everything worked like a charm! When I was done, I tried running the tests in the igibson/tests folder. Most of them ran fine, but 3 of them need to be updated (seems to be just a matter of fixing the imports and asset paths):

- test_glfw_renderer.py
- test_vr_system.py
- test_vr_rendered_ohoopee.py

**Comment by ChengshuLi** [comment]
Thanks for reporting this. We have removed these outdated tests in our next release.
