### ISSUE TITLE
Missing 'non_sampleable_categories.txt' ?

### ISSUE THREAD

**Issue by evanchugh** [StanfordVL/iGibson#115]
Upon downloading the assets and running
`python -m igibson.examples.demo.demo_static`

I get the following error: FileNotFoundError: [Errno 2] No such file or directory: '/home/evan/miniconda3/envs/igibson/lib/python3.8/site-packages/igibson/data/ig_dataset/metadata/non_sampleable_categories.txt'

I've tried reinstalling to no avail.

**Comment by ChengshuLi** [comment]
Could you try to uninstall cmake in your conda env?

**Comment by fxia22** [comment]
can you try a standalone `from cmake import cmake` and in command line `cmake --version`?

**Comment by DhruvaBansal00** [comment]
Not sure if this is helpful, but I was able to install iGibson from source and run the demo. The PyPI version still throws the `FileNotFoundError` mentioned earlier in this issue.

**Comment by fxia22** [comment]
@DhruvaBansal00 thanks for reporting this, the pypi version has been updated.

**Comment by ChengshuLi** [comment]
Please feel free to re-open the issue if the problem persists. Thanks!
