### ISSUE TITLE
Where are the iGibson 2.0 tasks and RL Training code in those tasks

### ISSUE THREAD

**Issue by arthur801031** [StanfordVL/iGibson#121]
In the [iGibson 2.0 paper](https://arxiv.org/pdf/2108.03272.pdf), there are six novel tasks: Grasping Book, Soaking Towel, Cleaning Stained Shelf, Cooking Meat, Slicing Fruit, and Bi-Manual Grasping. 

1. Where are these tasks defined (they're not in the `igibson/tasks` folder)?
2. Where is the RL training code for those tasks (shown in the paper's 6. Evaluation - Experimental Results)? What is the command for training the SAC algorithm on those tasks?

Thank you.

**Comment by ChengshuLi** [comment]
We have not released these task setups and training pipelines yet, but we plan to do so in the near future. Stay tuned.
