### ISSUE TITLE
ERROR:root:Optimized renderer is not supported on Mac

### ISSUE THREAD

**Issue by ArbiterGe** [StanfordVL/iGibson#122]
In the Macbookair can't render in the enviroment when I Compile source code to install iGibson
when I run env_example.py
find problem：
WARNING:root:Rendering both iggui and pbgui is not supported on mac, choose either pbgui or iggui. Default to iggui.
INFO: Probing, EGL cannot run on this device
INFO:root:Using device 0 for rendering
ERROR:root:Optimized renderer is not supported on Mac

**Comment by ArbiterGe** [comment]
My macbook is macbook air m1

**Comment by shivanimall** [comment]
Facing the same issue as OP

**Comment by ArbiterGe** [comment]
> Facing the same issue as OP when running any file that requires iggui eg: `mouse_interaction.py`, `env_interactive_example.py`
> noting that have been successfully connecting to pybullet GUI.
I set the parameter “optimization” to false

**Comment by ArbiterGe** [comment]
I set the parameter "optimization" to false

**Comment by shivanimall** [comment]
which file is that?

**Comment by ChengshuLi** [comment]
Feel free to try this. 
```
settings = MeshRendererSettings(optimized=False)
simulator = Simulator(rendering_settings=settings)
```
