### ISSUE TITLE
EGL issue when sshing

### ISSUE THREAD

**Issue by ericrosenbrown** [StanfordVL/iGibson#125]
We are participating in the BEHAVIOR challenge and have gone through the installation process for iGibson provided in the instructions. However, whenever we ssh into our machine with the setup and try to run a script, like:

python -m igibson.examples.demo.env_example

The script simply fails to run and gives the following error:

INFO: Probing, EGL cannot run on this device
INFO:root:Using device 0 for rendering
ERROR: Failed to EGL with glad.

We have received this issue when sshing into our machine using a Mac and a Ubuntu 16.04 machine. Is there something we need to do to make sure we can ssh into a computer and run iGibson correctly?

**Comment by ChengshuLi** [comment]
https://github.com/StanfordVL/iGibson/blob/master/igibson/examples/demo/env_example.py uses "gui" mode, and I think you are accessing a headless server via ssh.

Try to use `mode='headless'` instead.

**Comment by fxia22** [comment]
Hi Eric, it looks like your ubuntu machine doesn't have OpenGL/EGL installed?

You can take a look at our trouble shooting guide http://svl.stanford.edu/igibson/docs/issues.html
and installation guide: http://svl.stanford.edu/igibson/docs/installation.html

**Comment by mjlbach** [comment]
Please reopen if EGL issues persist.
