### ISSUE TITLE
Matterport Dataset floors.txt missing

### ISSUE THREAD

**Issue by elhamAm** [StanfordVL/iGibson#128]
The original GibsonEnv codebase worked with Matterport but this newer version of the simulator requires a floors.txt for the environments. Is there a way to generate it or does your team have a copy of the required files? I know this issue has been resolved for the 3d2d dataset but it hasn't been resolved for the Matterport dataset

I downloaded using the command python2 download_mp.py --task_data gibson -o .

and download_mp.py is from the email address matterport3d@googlegroups.com (I followed the instructions here : https://github.com/StanfordVL/GibsonEnv/blob/master/gibson/data/README.md)

**Comment by fxia22** [comment]
@elhamAm thanks for the question, can you follow this guide to generate `floors.txt` for matterport scans? https://github.com/StanfordVL/iGibson/tree/master/igibson/examples/gen_data

we will try to work with the matterport3d team to update a pre-processed version for iGibson.

**Comment by fxia22** [comment]
@elhamAm we worked with matterport3d team and provided a pre-processed version. You can request `download_mp.py` again and download with `python2 download_mp.py --task_data igibson -o .`

**Comment by ChengshuLi** [comment]
@elhamAm Could you please follow the new documentation we added here? 
http://svl.stanford.edu/igibson/docs/dataset.html#download-matterport3d-scenes
Thanks!

**Comment by ChengshuLi** [comment]
Please feel free to re-open this issue if the problem persists.
