### ISSUE TITLE
About different rendering modes

### ISSUE THREAD

**Issue by EdgeOBerJY** [StanfordVL/iGibson#129]
Hi, I am still kind of confused about different rendering modes. There are 3 issues that I wanna figure out.
1. It seems that in 'MeshRenderer', there are 7 modes, while in 'MeshRendererG2G' there are 6, lacking 'ins_seg'. Is there any reason why 'ins_seg' is not available on GPU?
2. I tried to visualize 'seg' and 'ins_seg' rendering from the same scene, and it turned out that not only segment numbers but also segment colors are not the same. I multiply the values by MAX_CLASS_COUNT, and the results are even not quite equal between the twos. 'seg' is [0, 4, 6, 34], while 'ins_seg' is [0, 1, 1.5, 2, 3.5, 4]. What causes such a difference? PS: I consider MAX_CLASS_COUNT=512.
3. In '3d' and 'optical_flow' modes, the output array is not strictly located within [0, 1]. I'd like to know what values in '3d', 'scene_flow', 'optical_flow' exactly mean?

**Comment by cgokmen** [comment]
Hi,

Sorry for the very late response (I'm cleaning up github issues) - we have fixed the MeshRendererG2G issue, the ins_seg and seg modality use cases documented here: https://stanfordvl.github.io/iGibson/renderer.html#about-the-semantic-segmentation-image  (so there are different max counts for the class and instance versions).

As for the 3d mode, the 3 channels contain the position of the 3d point hit at that pixel, relative to the camera, in the opengl coordinate frame.

As for scene_flow and optical_flow I think @fxia22 might be able to help.
