### ISSUE TITLE
Explore the enviroment to find some object

### ISSUE THREAD

**Issue by asfandasfo** [StanfordVL/iGibson#131]
Hi, is there any option to explore the environment to find an object?

Thanks

**Comment by mjlbach** [comment]
While we include some built-in examples (see the example directory), we do not include any explicit exploration policies or primitives. Feel free to contribute an example implementation. Our examples are only provided to align with the published iGibson (1.0 and 2.0)/BEHAVIOR papers, and for didactic purposes.
