### ISSUE TITLE
Error on windows10

### ISSUE THREAD

**Issue by 1625368821** [StanfordVL/iGibson#132]
why?

(igibson) PS C:\Users\16253\anaconda3\iGibson> python -m igibson.examples.demo.demo_static
INFO:root:Importing iGibson (igibson module)
INFO:root:Assets path: C:\Users\16253\anaconda3\iGibson\igibson\data/assets
INFO:root:Gibson Dataset path: C:\Users\16253\anaconda3\iGibson\igibson\data/g_dataset
INFO:root:iG Dataset path: C:\Users\16253\anaconda3\iGibson\igibson\data/ig_dataset
INFO:root:3D-FRONT Dataset path: C:\Users\16253\anaconda3\iGibson\igibson\data/threedfront_dataset
INFO:root:CubiCasa5K Dataset path: C:\Users\16253\anaconda3\iGibson\igibson\data/cubicasa_dataset
INFO:root:iGibson Key path: C:\Users\16253\anaconda3\iGibson\igibson\data/igibson.key
INFO:root:Example path: C:\Users\16253\anaconda3\iGibson\igibson\examples
INFO:root:Example config path: C:\Users\16253\anaconda3\iGibson\igibson\examples\configs
pybullet build time: Oct 14 2021 21:15:57
ERROR: Failed to create GLFW window.

**Comment by mjlbach** [comment]
Need more information. We've tested on our old machines and current machines without issue. Ensure you have the latest nvidia drivers installed, have removed prior build artifacts (rm -rf build), and have MSVC installed via visual studio 2017.
