### ISSUE TITLE
Fix/upgrade collision checking for navigation

### ISSUE THREAD

**Issue by NishanthJKumar** [StanfordVL/iGibson#133]
I noticed there's currently a `TODO` comment in `utils/behavior_robot_planning_utils.py/plan_base_motion_br/collision_fn`. Some colleagues and I are trying to use the `plan_base_motion_br` and have noticed that while the waypoint plans returned are correct, executing them results in all sorts of collisions with various furniture. Is it possible to address this todo and incorporate good collision checking for this function anytime soon? If not, if you could provide some pointers on what needs to be done to get this to work correctly, I'd be happy to complete this `TODO` and open a PR. Thanks!

**Comment by NishanthJKumar** [comment]
Closed because we discovered that collision checking is in fact happening correctly and the collisions we were observing were caused by an entirely different phenomenon.

**Comment by cgokmen** [comment]
Hi Nishanth,

Sorry I did not notice this issue report earlier - we actually have iterated on these motion planning functions a bit and will be releasing an updated version soon in a new release we will cut in the upcoming week or so. Please stay posted - I will try to send an update here too once the release is out.

Cem

**Comment by NishanthJKumar** [comment]
Sounds good, looking forward to the new release! Thanks so much Cem :+1:
