### ISSUE TITLE
JSON Serialization Potential Bug In Behavior Examples

### ISSUE THREAD

**Issue by brandontrabucco** [StanfordVL/iGibson#138]
Hello SVL,

I have installed the igibson sim, bddl, and behavior benchmark as per the instructions provided at https://docs.google.com/document/d/1u2m9Ld6Qo3eG-fvCzuAZN6lHxwpVVBlwLVdzo_WDlNI. I can also instantiate the behavior simulator and see both the environment PyBullet is rendering, and the robot models.

However, the install check provided in the doc does not work for me.

I'm running: `python iGibson/igibson/examples/behavior/behavior_env_metrics.py`.

However, this command exits with an error after running for a while:

```
Traceback (most recent call last):
  File "iGibson/igibson/examples/behavior/behavior_env_metrics.py", line 95, in <module>
    json.dump(per_episode_metrics, file)
...
TypeError: Object of type float32 is not JSON serializable
```

I think my installation of the simulator is correct, as per_episode_metrics is populated with data seemingly correctly. Perhaps there is a bug in how the episode data is being written to JSON (should it be converted to a list first?).

Best,
Brandon

**Comment by mjlbach** [comment]
This will be fixed in the next release (the json in this example was only for didactic purposes).

If you want to patch your local install you can apply the following patch.

```
diff --git a/igibson/metrics/agent.py b/igibson/metrics/agent.py
index fe195c65..1ebb8d80 100644
--- a/igibson/metrics/agent.py
+++ b/igibson/metrics/agent.py
@@ -160,7 +160,7 @@ class FetchRobotMetric(MetricBase):
         gripper_distance = np.abs(delta_pos)
         self.delta_agent_distance["gripper"].append(gripper_distance)
 
-        self.agent_local_pos["gripper"].append(list(robot.get_relative_eef_position()))
+        self.agent_local_pos["gripper"].append(robot.get_relative_eef_position().tolist())
 
         contacts = p.getContactPoints(bodyA=robot.robot_ids[0], linkIndexA=robot.eef_link_id)
         if len(contacts) > 0:
```
