### ISSUE TITLE
Loading an external 3D model to iGibson

### ISSUE THREAD

**Issue by asfandasfo** [StanfordVL/iGibson#140]
Hi, I was trying to load my own 3D model. The original model is in .blender format. I exported it to .obj format and followed the instructions [here](https://github.com/StanfordVL/iGibson/tree/master/igibson/examples/gen_data) but couldn't generate the floor.txt.

**Comment by roberto-martinmartin** [comment]
what is the error?

**Comment by asfandasfo** [comment]
> what is the error?

@roberto-martinmartin 
<img width="573" alt="error" src="https://user-images.githubusercontent.com/11736209/142696745-9a6cf619-17b2-4439-9a3f-f291401027cf.png">

**Comment by roberto-martinmartin** [comment]
Looking at the code of the assert, it looks like your mesh has more than 2 faces (triangles) connected to the same edge. Sounds like a malformed mesh. The library we use to process the meshes (meshcut) requires edges to connect max 2 triangles. Maybe you can clean the input mesh before processing it with our script to remove those cases.

this is the code from meshcut that triggers the asset:
```
# Sanity check : max 2 faces per edge
for e, tris in self.edges_to_tris.items():
    assert len(tris) <= 2
```

**Comment by asfandasfo** [comment]
@roberto-martinmartin I tried this with matterport scene(17DRP5sb8fy) as well and got the same assertion error. After cleaning the input, I'm getting this.
<img width="572" alt="Screenshot 2021-12-03 at 11 52 26" src="https://user-images.githubusercontent.com/11736209/144590660-ec14dbc2-fa03-4db3-a074-a22539f2ff69.png">

**Comment by fxia22** [comment]
You can try commenting out the assertion in meshcut code.

**Comment by asfandasfo** [comment]
> You can try commenting out the assertion in meshcut code.
> […](#)
> On Dec 3, 2021, at 02:53, recluze ***@***.***> wrote: ﻿ @roberto-martinmartin I tried this with matterport scene(17DRP5sb8fy) as well and got the same assertion error. After cleaning the input, I'm getting this. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

Still same error...

https://user-images.githubusercontent.com/11736209/144590660-ec14dbc2-fa03-4db3-a074-a22539f2ff69.png

**Comment by asfandasfo** [comment]
@fxia22 @roberto-martinmartin 

Thanks, I am able to solve this issue with matterport scene but still struggling loading my own model.

**Comment by roberto-martinmartin** [comment]
let us know if you have further questions but it looks like a mesh formatting issue. I'll close the issue, feel free to reopen with more details

**Comment by asfandasfo** [comment]
> let us know if you have further questions but it looks like a mesh formatting issue. I'll close the issue, feel free to reopen with more details

Hi, I was managed to load my own model without errors but I don't see anything in pybullet. When I checked the external view I see my model loaded inside a different Gibson scene with weird texture. Any suggestions on what could be the problem?
<img width="978" alt="Screenshot 2022-01-10 at 12 03 10" src="https://user-images.githubusercontent.com/11736209/148756927-bd047f2e-b225-4a76-b9e1-a06b8b2763da.png">
