### ISSUE TITLE
Fetch robot default arm position

### ISSUE THREAD

**Issue by kamalesh0406** [StanfordVL/iGibson#155]
I have been trying to set the default position of the arms in the fetch robot in the tucked position as suggested by the docs. But it seems that in the latest version of iGibson, the arms are left in the untucked position while calling the reset function. I was able to change the code in the library myself and able to set the arms in the tucked position.

However, I would prefer if we had an argument in the config file for the user to choose between the tucked and the untucked position instead of having to read through the codebase to find the functionality. I would be glad to write required code and create a pull request if you are interested in this feature.

**Comment by roberto-martinmartin** [comment]
Hi @kamalesh0406 ,
sorry for the delay. Please, check the latest controller version as it includes this kind of functionality. However, it is not directly providing an interface to specify if the (manipulation) robot is preferred to be in tucked or untucked configurations after reset. this could be a controller option. 

Feel free to add it and submit a pull-request for us to integrate

Thanks!
