### ISSUE TITLE
Need help find `igibson.envs.behavior_env`

### ISSUE THREAD

**Issue by jing-bi** [StanfordVL/iGibson#157]
Dear author,

I found this package `igibson.envs.behavior_env` is used in both `behavior_mp_env.py` and BEHAVIOR dataset, but i cannot find it in the master brench.

Do i need to switch to another brench or past commit to find it?

**Comment by jing-bi** [comment]
Found it in the past commit.

**Comment by ToddBear** [comment]
Hi jing-bi, i met the same problem. I wonder how you solved it ?
