### ISSUE TITLE
cannot extract anything useful from mesh

### ISSUE THREAD

**Issue by jing-bi** [StanfordVL/iGibson#159]
I'm trying to replay the raw behavior hdf5 file with demo replay script, but when running there are lots of warning messages like:

`iGibson/igibson/data/ig_dataset/scene_instances/20220125-102157_1714404359879452993_83744/: cannot extract anything useful from mesh`
`arning[examples/SharedMemory/plugins/tinyRendererPlugin/TinyRendererVisualShapeConverter.cpp,558]:
issue extracting mesh from COLLADA/STL file`

I'm not sure if this is normal or there is something wrong.

btw, the demo task will eventually fail to replay.

Thanks for any help you can offer!

**Comment by roberto-martinmartin** [comment]
This happens when trying to use encrypted assets without decrypting them or vice versa. 
Could you get the latest ig_dataset and check that the license is in the right folder?
Thanks
