### ISSUE TITLE
Dynamic robot and object spawning

### ISSUE THREAD

**Issue by CharlesAverill** [StanfordVL/iGibson#165]
Is there an official way to dynamically spawn a robot into an iGibson house scene? Our team has a jury-rigged process we've been using involving pathfinding between random points sampled from the floor, but I would imagine there is an officially-supported way to accomplish this.

Our goal is to spawn a robot that has a table with some objects atop it directly in front of the robot. We'd like to use the house scenes to get some variety for our dataset creation, as the robot's field of vision will include some of its surroundings as well.

This is trivial for the EmptyScene, but has been hard to get around for the house scenes.

**Comment by sycz00** [comment]
Perhaps you could take a look at` env.test_valid_position(object, pos, orn)` to verify that the object gets there without collision and `env.land(obj_list[0], pos, orn)` for landing the object. Furthermore, use 
`_, initial_pos = env.scene.get_random_point(floor=self.floor_num)` to sample a new position (robot or object) and use 
`reset_success = env.test_valid_position(env.robots[0], initial_pos, initial_orn)` to check if the spawn point for the agent is a proper choice.

**Comment by cgokmen** [comment]
What are the requirements re: the sampled position? The method recommended above by @sycz00 sounds reasonable.

**Comment by CharlesAverill** [comment]
@sycz00 Thank you for the tips, we'll be trying this very soon! @cgokmen I agree that the solution good. As for requirements, we would just like to find a position with enough space to spawn a table and robot, consistently.

**Comment by roberto-martinmartin** [comment]
Closing this issue. Feel free to reopen
