### ISSUE TITLE
Running multiple envs simultaneously

### ISSUE THREAD

**Issue by meier-johannes94** [StanfordVL/iGibson#167]
If I plan to run multiple environments simultaneously, how much RAM and GPU RAM should I reserve per environment?

**Comment by cgokmen** [comment]
from a colleague who has run such experiments:

> it depends on the scene size, on average probably the following?
> gpu ram: 2 gb
> cpu ram: 5 gb

YMMV :)

**Comment by meier-johannes94** [comment]
Thanks a lot!
