### ISSUE TITLE
Low FPS in Non-Headless Mode

### ISSUE THREAD

**Issue by GaganBhat** [StanfordVL/iGibson#169]
During headless mode in a demo scene, I can see around ~70-80 FPS. 

However, when the visualization is done the FPS drops to an incredibly low 5-7 FPS. 

This is with an RTX A5000 and Intel i9 machine. Is this level of performance expected?

I'm running the non interactive example with random actions taken. https://github.com/StanfordVL/iGibson/blob/master/igibson/examples/environments/env_nonint_example.py

**Comment by cgokmen** [comment]
Hi, what are you trying to use iGibson for? The particular demo you are running uses a Gibson scene and not an iGibson one - these scenes are from the first Gibson paper where non-interactive scenes were built out of 3d scans of real environments. I wonder if that is the reason - are you intentionally trying one of these scenes, or are you trying to use our interactive scenes (from the iGibson papers)?

**Comment by penttinj** [comment]
Hi, I've also noticed that version 2.0.6 causes a huge performance drop for the non-interactive example. 2.0.5 runs at 21-24 FPS while 2.0.6 runs the same 5-7 FPS as OP.

**Comment by ChengshuLi** [comment]
Thank you for reporting the performance regression. We are currently working on it and will get back to you.

**Comment by GaganBhat** [comment]
@cgokmen I am using iGibson primarily for exploration algorithms for Fetch in previously unseen environments. In this use case, I'm primarily using the Matterport3D dataset which contains non-interactive 3D scans of real environments.

**Comment by cgokmen** [comment]
Thanks for the reports - we have fixed the issue and will be releasing the fix in a few hours.

**Comment by cgokmen** [comment]
@GaganBhat and @penttinj thanks again for both of your reports - we have released iGibson 2.1.0 which corrects this issue, feel free to switch to that. Let us know if you still run into issues.
