### ISSUE TITLE
Do I need a super power CPU/ large memory to run the stable_baseline3 example?

### ISSUE THREAD

**Issue by genkv** [StanfordVL/iGibson#176]
Hi, I know this might not be directly relative to iGibson but I would really appreciate some comments or experience from the community.

I'm trying to run the stable_baseline3_example located in the examples folder. I noticed that total_timestamps is set to 1 million and number of multi-process environments (num_environments) is set to 8.

When I try to run this code, my system would first complain that it's unable to allocate a 56.4G array. So I modified the value of /proc/sys/vm/overcommit_memory to 1 to at least get the program started. But the process will always get killed by daemon after around 4000 timesteps (in total). I think it's because the overcommit hits certain threshold.

I'm curious if anyone was able to successfully train the model. If so, what's your hardware specs? Or did you modify anything in the code? I also tried to lower the total_timestamp to 10k and num_environments to 1. But the trained model with so little timesteps would end up only making the robot to turn around in circles when I apply it in an eval environment.

Here's my specs:
GPU: A2000 12GB
Memory: 46GB
CPU: i7-10700 CPU 2.90GHz × 16
SSD with enough free space

Thanks

**Comment by mjlbach** [comment]
IIRC we trained it with 64 gb ram, so you just need more ram. You need to train it for around 1 million steps. It should not take too long, a couple hours at most.

**Comment by genkv** [comment]
> IIRC we trained it with 64 gb ram, so you just need more ram. You need to train it for around 1 million steps. It should not take too long, a couple hours at most.

Thank you. I added more RAM and it helped :)

**Comment by genkv** [comment]
> > IIRC we trained it with 64 gb ram, so you just need more ram. You need to train it for around 1 million steps. It should not take too long, a couple hours at most.
> 
> Thank you. I added more RAM and it helped :)

I was able to train the model with 1 millions steps. And wrote some code to visualize the using of model on a robot in the environment. But all it does is spinning around rapidly without moving anywhere. Must be something wrong with how I implement the visualization of testing the model?


```
config_file = "turtlebot_nav.yaml"
    env = iGibsonEnv(
        config_file=os.path.join(igibson.configs_path, config_file),
        mode="gui_interactive",
        action_timestep=1 / 10.0,
        physics_timestep=1 / 120.0,
        use_pb_gui=False
    )

s.viewer.initial_pos = [-2, 1.4, 1.2]
s.viewer.initial_view_direction = [0.6, -0.8, 0.1]
s.viewer.reset_viewer()

model = PPO.load(sys.argv[1], env=env)
obs = env.reset()

for _ in range(1000):
        with Profiler("Simulator step"):
            action, _states = model.predict(obs, deterministic=True)
            obs, rewards, dones, info = env.step(action)
            rgb = s.renderer.render_robot_cameras(modes=("rgb"))

```

**Comment by cgokmen** [comment]
@genkv if you can post what the issue was / how you solved it perhaps it'll be helpful for other users too in the future. Thanks!

**Comment by genkv** [comment]
> @genkv if you can post what the issue was / how you solved it perhaps it'll be helpful for other users too in the future. Thanks!

@cgokmen The follow up question is actually quite practical: how do you properly apply a trained model in iGibson? I closed this issue and opened a new one dedicated to the follow-up question. Haven't figured out an answer yet. I will post updates once I have one.

Thank you.
