### ISSUE TITLE
Different window resolution for Viewer and RobotViewer

### ISSUE THREAD

**Issue by genkv** [StanfordVL/iGibson#186]
Viewer provides an interactive display of the world while RobotView displays one of the observation spaces -- the rgb camera. I noticed that they use the same renderer that results both the Viewer and the RobotView having the same window size, which is the rgb camera resolution.

Is there any way I can scale up the Viewer window resolution for a better visualization experience? Usually the rgb camera resolutions are relatively low.

**Comment by ChengshuLi** [comment]
Unfortunately, we don't have a good way to use different window resolutions for different views for now. I agree it would be a good feature to have. Feel free to file a PR on this if you want!

Meanwhile, you can increase image_width and image_height in the config file or in the constructor of the Simulator.

**Comment by genkv** [comment]
> Unfortunately, we don't have a good way to use different window resolutions for different views for now. I agree it would be a good feature to have. Feel free to file a PR on this if you want!
> 
> Meanwhile, you can increase image_width and image_height in the config file or in the constructor of the Simulator.

Thank you. I would file a PR when I implement this feature.
