### ISSUE TITLE
can we build our own environment and import it into igibson?

### ISSUE THREAD

**Issue by Gengshucheng** [StanfordVL/iGibson#187]
excuse me, I wonder if I can build my own 3d environment and import it into igibson? if I can ,what should I do?How to build it?Thank you

**Comment by ChengshuLi** [comment]
You can scan (using a Matterport scanner or even your cell phone) and 3D-reconstruct your own 3D environment, and then use StaticIndoorScene to load it. https://github.com/StanfordVL/iGibson/blob/b1521122c1d39dbf392012b6fc0af99cbc62fcb7/igibson/scenes/gibson_indoor_scene.py#L15

**Comment by ChengshuLi** [comment]
Feel free to re-open the issue if you have further questions.
