### ISSUE TITLE
Unable to get robot_mass correctly in InteractiveNavRandomTask

### ISSUE THREAD

**Issue by sanghongrui** [StanfordVL/iGibson#192]
I'm trying to train an  `InteractiveNav` agent,  but I find that the pybullet cannot access the right robot mass. 
I bulild igibson from source using cvpr21_challenge branch. In file `gibson2/tasks/interactive_nav_random_task.py`, the column 24 `self.robot_mass = p.getDynamicsInfo(env.robots[0].robot_ids[0], 0)[0]`  always return 0.  
As a result, `info['kinematic_disturbance']`, `info['dynamic_disturbance']` and `info['effort_efficiency']` can not calculate properly. 
I use the `gibson2/examples/configs/turtlebot_interactive_nav.yaml` provided by igibson as config file , did I ignore some key configurations in it?

**Comment by sanghongrui** [comment]
As described in [pybullet quickstart guide](https://usermanual.wiki/Document/pybullet20quickstart20guide.479068914/html#pf1d), the parameter `link_id` in `getDynamicsInfo(bodyUniqueId, link_id)` is link(joint) index or -1 for the base. Therefore, I think the column 24 `self.robot_mass = p.getDynamicsInfo(env.robots[0].robot_ids[0], 0)[0]` sholud modify to `self.robot_mass = p.getDynamicsInfo(env.robots[0].robot_ids[0], -1)[0]`.

**Comment by cgokmen** [comment]
@ChengshuLi @cremebrule fyi

**Comment by ChengshuLi** [comment]
Yes, your fix is corrrect! Feel free to re-open the issue if you have further questions.
