### ISSUE TITLE
the pybullet has no texture

### ISSUE THREAD

**Issue by Gengshucheng** [StanfordVL/iGibson#197]
hey, I want to know, when I add the argument use_pb_gui = True，the scene is loaded very slow ,and there is no texture, just the bule、yellow and red color.

**Comment by mjlbach** [comment]
The pybullet viewer is extremely slow at loading large textures outside of iGibson. Due to an agreement with our asset provider, all of our textures are encrypted. We provide an encrypted texture renderer in iGibson, but pybullet does not have this ability.
