### ISSUE TITLE
Example file for navigating like Gibson version 1?

### ISSUE THREAD

**Issue by chaundm** [StanfordVL/iGibson#20]
Hi Fei Xia,

I would like to find a file in Gibson version 2, such as play_husky_camera.py like Gibson version 1. Do you have any file like that to navigate the agent?

**Comment by Berk035** [comment]
I wonder it too. Thanks.

**Comment by roberto-martinmartin** [comment]
This is an old message but in case someone looks for it in the future, you can look in the branch https://github.com/StanfordVL/iGibson/tree/cleanup-robot-demos and run the example robot_control_example.py. Selecting the husky robot with teleoperation and differential drive control leads to the same behavior as in the play_husky_camera.py of the Gibson paper. It should be easy to extract those options into its own application bypassing the selection procedure

**Comment by roberto-martinmartin** [comment]
this example will be moved into master in the next days
