### ISSUE TITLE
How to Find Area of a scene? 

### ISSUE THREAD

**Issue by vbalaji21** [StanfordVL/iGibson#203]
I want to find the area of a scene in general and specifically the area of a corridor or room.
Is this information given in metadata.json
If so can you tell me this with an example of a scene like kingfisher or Broseley.

**Comment by ChengshuLi** [comment]
For the area of scene, you can compute it using the traversable map. 
For scenes in the Gibson dataset like the ones you mentioned, unfortunately, we do not have the room segmentation.
