### ISSUE TITLE
Cannot open pybullet

### ISSUE THREAD

**Issue by xyuang01** [StanfordVL/iGibson#204]
Hey guys, it seems that I have downloaded pybullet but is unable to run it on my computer. Do you guys know why it goes "not responding"?
![pybullet problems](https://user-images.githubusercontent.com/56892766/168894525-44ce7ace-41ad-4bea-af39-e412f3303787.png)
![installed_pybullet](https://user-images.githubusercontent.com/56892766/168894548-3b491fd5-7611-4714-af9d-474faf333540.png)

**Comment by roberto-martinmartin** [comment]
No idea but this seems to be a purely a question about pybullet, not iGibson, right?
Some things:
- you seem to pip install without virtual environment. Taht is usually not recommended
- we have our own version of pybullet to be used with iGibson. if you are trying to use iGibson, you'll need that

Good luck!
