### ISSUE TITLE
upgraded iGibson version

### ISSUE THREAD

**Issue by sycz00** [StanfordVL/iGibson#208]
Hey folks,

I have a tiny question, I upgraded my iGibson project to the latest version and had to realize that there exist no more "gui" mode ? only "gui_interactive" which was previously "ig_gui" ? I really appreciate the pybullet window,  customly zooming in and out.

Perhaps I couldn't find the corresponding name

EDIT: just pass "use_pb_gui=True" to the iGibsonEnv()

**Comment by roberto-martinmartin** [comment]
Yes, use_pb_gui = True should do the trick!
