### ISSUE TITLE
Releasing a dataset based on iGibson environments

### ISSUE THREAD

**Issue by felipefelixarias** [StanfordVL/iGibson#209]
Hello, I would like to release a dataset of annotated iGibson traversability maps as part of a conference paper. The maps are annotated with visitation counts computed through crowd simulation (like in the CVPR 2021 Challenge). Below is a visualization of the annotations. Is there a procedure for releasing such data? I believe the current license would permit it, but I would appreciate further guidance. You can reach me at felipea2@illinois.edu or respond here. Thanks.
![Beechwood_1_int](https://user-images.githubusercontent.com/47954959/171870848-da7c0ae5-83fd-4d5f-b367-3e560f6cac6c.png)

**Comment by ChengshuLi** [comment]
Feel free to release the annotated iGibson traversability maps. Thank you for using iGibson :)
