### ISSUE TITLE
Re-instantiating environment within a loop

### ISSUE THREAD

**Issue by zubair-irshad** [StanfordVL/iGibson#21]
I am re-instantiating TurtlebotNavigateSpeedControlEnv in a for loop. In the headless, display_ui =false mode, I get the following error at finish loading shaders:

terminate called after throwing an instance of 'zmq::error_t'
what(): Address already in use

It seems like the environment is not terminating correctly before re-instantiating. Is there a way to terminate the environment after a loop is finished?

@fxia22  @hzyjerry Any leads would be appreciated. Thanks in advance!

**Comment by fxia22** [comment]
`zmq` was no longer used in later version of iGibson. I am closing this issue.
