### ISSUE TITLE
I have two  questions about the turtlebot view and pedestrain

### ISSUE THREAD

**Issue by Gengshucheng** [StanfordVL/iGibson#212]
1、In the robot view, the above and below of the image are black, this may influence the learning,can I adjust it?
2、I want to import some Pedestrains in the scene, then how can I drive the Pedestrain with the social-forces model ORCA？
 Is there any tutorial for these two questions？
![turtlebot相机视角](https://user-images.githubusercontent.com/74408885/172578258-4523419e-7fb8-4d68-aecd-267002a75ccb.png)
![驱动行人](https://user-images.githubusercontent.com/74408885/172578384-58feb672-6ab8-4f66-9384-ba4817a06570.png)

**Comment by THU-Bohr** [comment]
Hello, which operating system did you use to install igibson? Which version? thank you

**Comment by Gengshucheng** [comment]
> 
ubuntu20.04, igibson = 2.1.0

**Comment by Gengshucheng** [comment]
> 

@THU-Bohr ubuntu20.04 and igibson=2.1.0

**Comment by roberto-martinmartin** [comment]
@Gengshucheng , for the robot issue, try setting it to be hidden https://github.com/StanfordVL/iGibson/blob/master/igibson/render/mesh_renderer/mesh_renderer_settings.py#L27

The best way to set this parameter will depend on how you create your environment

For the use of simulated humans, I defer to some of my colleagues, I haven't use them much

Thanks!

**Comment by roberto-martinmartin** [comment]
(in case it was not clear, the black stripes is the robot. these parts of the robot are visible in the images from the camera of the real robot because of its position, but if you are not planning to do sim2real, you may make the robot to be hidden for the camera with the rendering option I mentioned)

**Comment by Gengshucheng** [comment]
@roberto-martinmartin  thanks，It's useful for me.

**Comment by ChengshuLi** [comment]
@Gengshucheng For simulating pedestrians with ORCA, you can refer to this file:
https://github.com/StanfordVL/iGibson/blob/cvpr21_challenge/gibson2/tasks/social_nav_random_task.py

Make sure you install ORCA first: https://github.com/sybrenstuvel/Python-RVO2
