### ISSUE TITLE
URDF file '/data4/mdv0/cabinet/0007/part_objs/cabinet_0007.urdf' not found

### ISSUE THREAD

**Issue by chaundm** [StanfordVL/iGibson#22]
Hi Fei Xia,

Could you please let me know where is the URDF file? I am trying to execute command 
python cabinets_example.py
But it looks like that it missed URDF file 

![Screenshot from 2020-01-06 13-43-53](https://user-images.githubusercontent.com/11848133/71797822-af20bd80-308a-11ea-8ed0-16f9f0d51506.png)

**Comment by roberto-martinmartin** [comment]
This example has been deprecated. Thanks!
