### ISSUE TITLE
The locobot control

### ISSUE THREAD

**Issue by Zhaocka** [StanfordVL/iGibson#220]
Hello! If I get a series of sub-target points according to the motion plan, how should I control the locobot to go to these sub-target points?

**Comment by cgokmen** [comment]
Take a look at how we do this for another type of robot and context, perhaps it will help: https://github.com/StanfordVL/iGibson/blob/58ac14cf62949008b6851a5a95602cd5084edffd/igibson/action_primitives/starter_semantic_action_primitives.py#L599-L602

**Comment by Zhaocka** [comment]
Ok ，thank you for your reply.
