### ISSUE TITLE
[question] Are the 15 interactive iGibson scenes fully loaded with objects?

### ISSUE THREAD

**Issue by RachithP** [StanfordVL/iGibson#228]
Hello,

Silly question about the 15 interactive iGibson scenes. I'm trying to create a image dataset from these 15 interactive scenes, captured from random poses. This is the code I'm using to load the interactive scenes,
```
    render_settings = MeshRendererSettings(enable_shadow=True, msaa=True, enable_pbr=False)

    for scene_id in available_ig_scenes:
        
        print(f"Processing scene {scene_id}")

        sim = Simulator(
            mode="headless",
            image_width=64,
            image_height=64,
            rendering_settings=render_settings,
        )

        scene = InteractiveIndoorScene(
            scene_id,
            build_graph=True,
        )

        sim.import_scene(scene)

        ...

        sim.disconnect()
```
From the looks of these images, the scene looks empty. I don't think this is expected because they are supposed to be fully populated.
![8](https://user-images.githubusercontent.com/42787281/179874646-79d9ff45-459b-4353-bcbb-4f447e52243d.png)
![3](https://user-images.githubusercontent.com/42787281/179875300-45f7c676-ce82-4fe6-b49e-472736fc2c05.png)

I'm not sure what I'm missing here. It would be helpful if someone can point me towards loading these 15 scenes populated with objects.

**Comment by ChengshuLi** [comment]
@RachithP They should be fully populated. Can you try to query `scene.objects_by_name`? My guess is that some rooms happen to be empty, but most rooms shouldn't be. 

Feel free to re-open the issue if it's not resolved.
