### ISSUE TITLE
Large 3D reconstructed world import question

### ISSUE THREAD

**Issue by JasonLiu324** [StanfordVL/iGibson#229]
Hi guys, our team attends to import large 3D reconstructed world (larger than 1 GB) and the texture file is not easy to be combined into one texture file. I have downloaded the gibson dataset and matterport dataset, but their sizes are all no more than 200 MB. So I wonder that whether you considered or tried to import large 3D world into iGibson? Thank you！

**Comment by JasonLiu324** [comment]
OK, I have imported a large obj file (more than 800M) successfully in static scene, but the FPS is relatively slow (3~4). And when I failed to add robot in it or integrate it with ROS with exception of segment fault (core dumped). So I suppose that iGibson cannot handle large 3D constructed world.

**Comment by ChengshuLi** [comment]
@fxia22 Any ideas?
I would suggest maybe modifying the `texture_scale` to `0.5` and see if there is any speedup?

**Comment by JasonLiu324** [comment]
I have tired reducing the texture_scale to 0.5, and the FPS rises from 3-4  to 4-5.

**Comment by fxia22** [comment]
How large is the space itself? We have reconstructed large spaces and manage to represent it efficiently with a small 3d file. You can consider doing some mesh decimation to make it smaller, blender would be an excellent tool for that. [tutorial](https://www.youtube.com/watch?v=Yx9TvvnxCAM)

**Comment by fxia22** [comment]
I suspect the problem is not texture size, but it is caused by obj file with too many polygons.

**Comment by JasonLiu324** [comment]
@fxia22 Thanks for your reply! The space itself is about 500-600 square meters. We have tried downsampling using Blender to reduce the .obj file size, but it will cause some empty space which may harm robot movement. The vedio you provide is really helpful and I assume making such adjustment is very time-consuming lol.
