### ISSUE TITLE
Is the 2d3ds_for_igibson dataset broken?

### ISSUE THREAD

**Issue by SophieLeichtle** [StanfordVL/iGibson#238]
I've been trying to look at a variety of the available datasets as i need a framework for training a robot from visuals, and while a lot of scenes have a lot of artifacting the 2d3ds datasets seem outright broken.
![Screenshot from 2022-09-15 17-16-41](https://user-images.githubusercontent.com/76942714/190442081-cdf5a2fe-6c02-4dfd-9826-54ca64ac701f.png)
![Screenshot from 2022-09-15 17-17-21](https://user-images.githubusercontent.com/76942714/190442158-4076925f-fbec-4e8b-99ba-eec1cfc0b182.png)
![Screenshot from 2022-09-15 17-17-55](https://user-images.githubusercontent.com/76942714/190442271-ccad089c-ea56-4c2f-9670-bd3127eb3a58.png)

These screenshots are just from area1, but the other areas have similar issues. Is this a problem with the dataset or could there be something wrong with my installation?

**Comment by ChengshuLi** [comment]
@fxia22 Correct me if I am wrong, but I think this is expected behavior? 3d reconstruction is not perfect and 2d3ds dataset is from a few years ago: the local artifacts seem to be expected.

**Comment by SophieLeichtle** [comment]
makes sense, the artifacts just seem so strong that it doesnt really look like its very usable. just want to make sure its not something wrong with my installation to be safe
