### ISSUE TITLE
How to remove objects in simulator?

### ISSUE THREAD

**Issue by Xqle** [StanfordVL/iGibson#246]
I import an EmptyScene and some objects. After some operation, I want to remove some of those objects and import new objects. How can I remove objects in simulator?

**Comment by cgokmen** [comment]
We don't support removing the objects due to limitations with how pybullet tracks object IDs. You can either delete/create a new simulator, or you can just put the objects far enough away that they won't collide with anything, where pybullet will put them to sleep.
