### ISSUE TITLE
jr2_kinova.urdf end effector joints in assets_dev.tar.gz

### ISSUE THREAD

**Issue by nstepp** [StanfordVL/iGibson#25]
Between jr2_kinova_old.urdf and jr2_kinova.urdf, the end effector joints were removed (or made fixed).

While not explicitly about the code in this repository, I was not sure where else to ask about that. What was the reason for removing them? If I need to use the end effector joints, should I be able to put them back in by editing the urdf?

Should I be using a different asset set?

**Comment by fxia22** [comment]
You are using the correct asset set. We changed end effector to fixed because currently we don't have an application where we want to grip things with fingers. You can add those joints back and change `action_dim` to use them in your simulation.
