### ISSUE TITLE
AWS tokens in releases

### ISSUE THREAD

**Issue by vsoch** [StanfordVL/iGibson#255]
In case you didn't see this - I think this is your project?

https://tomforb.es/i-scanned-every-package-on-pypi-and-found-57-live-aws-keys/

I was at Stanford so I saw the name at the top of the list and wanted to contact you asap (in case that author didn't).

**Comment by fxia22** [comment]
Thanks for reaching out. Those aws accounts are no longer active so there is no immediate security risk. We will sanitize them in future releases.

**Comment by vsoch** [comment]
Awesome, thanks!
