### ISSUE TITLE
Space7 dataset for Gibson 2

### ISSUE THREAD

**Issue by MADHAVAN001** [StanfordVL/iGibson#27]
Where can I find the space7 dataset for Gibson Env 2?

Some attributes like floors seem to be missing from V1

I'm also looking for Stanford 2D3Ds and Matterport datasets for V2

**Comment by yj-Tang** [comment]
Hi, Have you found the space7 dataset? I also get stuck in the same problem.

**Comment by roberto-martinmartin** [comment]
If you fill out the [form](https://docs.google.com/forms/d/e/1FAIpQLScWlx5Z1DM1M-wTSXaa6zV8lTFkPmTHW1LqMsoCBDWsTDjBkQ/viewform) and click submit, you should be able to download 2d3ds_for_igibson.zip. Let us know if this works for you.

**Comment by ChengshuLi** [comment]
@MADHAVAN001 

For Stanford 2d3ds and Matterport3D dataset, we have updated our dataset and documentation. Could you follow this new documentation and try again? Thanks!
http://svl.stanford.edu/igibson/docs/dataset.html
