### ISSUE TITLE
Compiling with CUDA requires <GL/gl.h>

### ISSUE THREAD

**Issue by fxia22** [StanfordVL/iGibson#29]
Currently `pip install gibson2` might fail on machines without "GL/gl.h" header installed. While iGibson uses glad to load OpenGL, cuda-gl inter-operation still requires "GL/gl.h". One way to solve this issue is to install `mesa-common-dev`. 

`sudo apt install mesa-common-dev`

**Comment by bryanzhou008** [comment]
What can I do if I do not have sudo access?
