### ISSUE TITLE
How to get focal length in mm?

### ISSUE THREAD

**Issue by NaveenSehgal** [StanfordVL/iGibson#3]
i noticed that the .yaml configuration files had a parameter for FOV, is there any way to get the true focal length size in mm?

I collected some test runs in Gibson, with RGB and camera pose data. I'm now trying to project coordinates in the 2D RGB image to 3D world coordinates using the ground truth depth, however I'm having trouble finding the true focal length in mm.

**Comment by roberto-martinmartin** [comment]
Hi! You should be able to compute the focal length based on the resolution and the FoV. An example: https://photo.stackexchange.com/questions/97213/finding-focal-length-from-image-size-and-fov
