### ISSUE TITLE
Why don't I see Fetch's arm in RobotView?

### ISSUE THREAD

**Issue by Caselles** [StanfordVL/iGibson#30]
Hello, 

I was wondering if in the RobotView window, I'm able to see Fetch's arm when it is in the vision field of the robot?

I don't see it, but I might be misusing the software so if someone from the development team could tell me if this feature is supported or not, that would be very helpful. Thanks !

**Comment by fxia22** [comment]
Thanks for your question. By default, we don't render the robot body itself as some robots might have parts occluding its camera. It is written here:https://github.com/StanfordVL/iGibson/blob/master/gibson2/core/render/mesh_renderer/mesh_renderer_cpu.py#L757

If you want to render the robot body, you can simply change it from `self.render(modes=modes, hidden=[instance])`to `self.render(modes=modes)` We should have exposed this as a parameter passed to the renderer. We will update this in future releases.

**Comment by Caselles** [comment]
Thank you so much, it works as intended. 

Closing this issue.
