### ISSUE TITLE
Colorized mesh's in gui_interactive

### ISSUE THREAD

**Issue by sycz00** [StanfordVL/iGibson#312]
Hey,

I would like to know if there's any chance I can see the real textures of the objects in an igibson_scene using the gui mode ? I could not find any flag for it so far.

Thanks :)

**Comment by cgokmen** [comment]
You should normally be seeing these in gui_interactive (not the pybullet GUI right?). Can you send a screenshot of what you get instead?

**Comment by sycz00** [comment]
Hey,
no you are right, I use gui_interactive but everything is colored (I think it has been changed for iGibson 2.0) in the earlier versions I could see the real mesh files of the objects. Is there any way to get back to this ?
Tahnks

**Comment by mjlbach** [comment]
The textures are now encrypted, the pybullet gui cannot display the encrypted textures so it shows  solid primary colors. You can send a screenshot to confirm but this is almost certainly your issue, and there is not a fix other to use only the cv2 based iG viewer (we can't add our decryption pipeline to pybullet).

**Comment by sycz00** [comment]
Okay still thanks. Would have been nice for illustrations in a paper. Perhaps it can be added in the future :)

**Comment by mjlbach** [comment]
The regular iG viewer should work fine for this purpose.

**Comment by sycz00** [comment]
alright :)
