### ISSUE TITLE
Save images or videos in headless mode

### ISSUE THREAD

**Issue by user432** [StanfordVL/iGibson#320]
Hey! I'm trying to use iGibson 2.0 on a headless server. My installation and everything went fine but I just wanted to know if there's any way i can save images or videos from the simulator (either robot's ego or 3rd person perspective). Sorry if this is a very naive question, I'm pretty new to this. Thanks!

**Comment by cgokmen** [comment]
Hi, definitely - if you just want to get them from the robot's perspective as you run simulation using the Environment APIs, you can simply get the observation returned by env.step(), pick out the camera image, and save that as an image using PIL.Image APIs.

If you want to dive deeper and be able to manipulate the camera outside the typical robotics environment context (e.g. no robot, no physics, just photos with a particular purpose) you can take a look at this example: https://github.com/StanfordVL/iGibson/blob/1f52c347210628cbab4d6cdf5a3b4945aa60d38f/igibson/utils/derivative_dataset/pipeline.py#L157-L189 (this is unmerged development code, but you can do this in your own code - it's just to give you an idea)

Essentially the simulator.renderer.render() function gives you the image as a numpy array. You can use PIL or cv2 to save that in your desired format.

For videos, you can either just save all your frames in a directory and run ffmpeg offline later to combine them into a video, or you can use cv2's VideoWriter to write a video on the fly. I'd recommend ffmpeg.

I'm closing this now but feel free to reopen if you have more questions.
