### ISSUE TITLE
Qt plugin issue

### ISSUE THREAD

**Issue by oliviaylee** [StanfordVL/iGibson#324]
When running `python -m igibson.examples.environments.env_nonint_example` I encounter the following error (running on a cluster)

```
INFO:igibson.render.mesh_renderer.get_available_devices:Device 0 is available for rendering
INFO:igibson.render.mesh_renderer.get_available_devices:Command '['/iris/u/oliviayl/anaconda3/envs/igibson/lib/python3.8/site-packages/igibson/render/mesh_renderer/build/test_device', '1']' returned non-zero exit status 1.
INFO:igibson.render.mesh_renderer.get_available_devices:Device 1 is not available for rendering
qt.qpa.plugin: Could not find the Qt platform plugin "offscreen" in "/iris/u/oliviayl/anaconda3/envs/igibson/lib/python3.8/site-packages/cv2/qt/plugins"
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

Aborted (core dumped)
```
How should I download the offscreen Qt platform plugin?

**Comment by ChengshuLi** [comment]
This is because you are running on a cluster machine without a display (monitor) connected to it. 

You can either set `headless=True` in the line below or run the code on a machine that has a display. 

https://github.com/StanfordVL/iGibson/blob/7d9598278b95ec1039e1f4366c66b45346521e44/igibson/examples/environments/env_nonint_example.py#L13

**Comment by oliviaylee** [comment]
Hi Chengshu, thanks. If I installed iGibson via pip how should I set this? Or should I compile it from source instead?

**Comment by oliviaylee** [comment]
Hi Chengshu, thanks for your help. With headless rendering, is it possible to get an output of what would have been rendered (e.g. as a gif)? For instance the image showed [here](https://stanfordvl.github.io/iGibson/quickstart.html)
I am trying a lot of the rendering examples like [this](https://stanfordvl.github.io/iGibson/renderer.html) and they are (unsurprisingly) not working because it's a headless machine, but I was wondering if there's any way to get those outputs as a jpeg/gif.
