### ISSUE TITLE
Issues downloading datasets

### ISSUE THREAD

**Issue by oliviaylee** [StanfordVL/iGibson#325]
Hi, I get the following error trying to download these datasets in [this form](https://docs.google.com/forms/u/1/d/e/1FAIpQLScWlx5Z1DM1M-wTSXaa6zV8lTFkPmTHW1LqMsoCBDWsTDjBkQ/formResponse) (the second form in the [Datasets section](https://stanfordvl.github.io/iGibson/dataset.html) of the iGibson installation):

Gibson dataset for sim2real challenge 2020
`INFO:__main__:Downloading the full Gibson dataset from https://storage.cloud.google.com/gibsonchallenge/gibson-challenge-data.tar.gz
Traceback (most recent call last):
  File "my-path/anaconda3/envs/igibson/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "my-path/anaconda3/envs/igibson/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "my-path/igibson/utils/assets_utils.py", line 420, in <module>
    download_dataset(args.download_dataset)
  File "my-path/igibson/utils/assets_utils.py", line 327, in download_dataset
    urlretrieve(url, tmp_file, show_progress)
  File "my-path/anaconda3/envs/igibson/lib/python3.8/urllib/request.py", line 273, in urlretrieve
    reporthook(blocknum, bs, size)
  File "my-path/igibson/utils/assets_utils.py", line 28, in show_progress
    pbar.start()
  File "my-path/anaconda3/envs/igibson/lib/python3.8/site-packages/progressbar/progressbar.py", line 286, in start
    if self.maxval < 0: raise ValueError('Value out of range')
ValueError: Value out of range`

2D3DS for iGibson, 7 scenes (1.4GB)
`INFO:__main__:Downloading the full Gibson dataset from https://storage.googleapis.com/gibsonchallenge/2d3ds_for_igibson.zip
100% |###########################################################################################|
INFO:__main__:Decompressing the full Gibson dataset into my-path/igibson/data/g_dataset
gzip: stdin has more than one entry--rest ignored
tar: Child returned status 2
tar: Error is not recoverable: exiting now`

Also, what is the difference between the ig_dataset.tar.gz file in [this form](https://docs.google.com/forms/d/e/1FAIpQLScPwhlUcHu_mwBqq5kQzT2VRIRwg_rJvF0IWYBk_LxEZiJIFg/viewform) and the ig_dataset.tar.gz file in [this second form](https://docs.google.com/forms/u/1/d/e/1FAIpQLScWlx5Z1DM1M-wTSXaa6zV8lTFkPmTHW1LqMsoCBDWsTDjBkQ/formResponse)?

**Comment by ChengshuLi** [comment]
Sorry for the late reply. 

The two ig_dataset.tar.gz should be the same. You can do `wget https://storage.googleapis.com/gibson_scenes/ig_dataset.tar.gz` and then unzip it to `igibson/data/ig_dataset`. Hope this helps!
