### ISSUE TITLE
How to fixed object when collision?

### ISSUE THREAD

**Issue by whcpumpkin** [StanfordVL/iGibson#335]
Dear authors,

I want the object not to move when it collides with the robot. What should I do?
I set fixed_base and is_fixed to True, but when collision the object was still moved.
This is my code. Did I change something wrong?
```
for obj_idx in env.scene.objects_by_id:
        obj=env.scene.objects_by_id[obj_idx]
        if "robot" in obj.name.lower():
            continue
        if hasattr(obj,'is_fixed') and obj.is_fixed[0]==False:
            obj.is_fixed[0]=True
        if hasattr(obj,'fixed_base') and obj.fixed_base==False:
            obj.fixed_base=True
```

**Comment by cgokmen** [comment]
You can't change whether the object is fixed after it is loaded, you need to do it beforehand. The easiest way to do this is going into the scene URDF file you are loading and replacing all the relevant `type="floating"` with `type="fixed"`. The URDF files are located in `igibson/data/ig_dataset/scenes/{scene_name}/urdf` - the default is `{scene_name}_best.urdf` but if you're loading a task instance then you need to use the URDF file corresponding to the task.
