### ISSUE TITLE
There is no "inside" supporting_surfaces in some objects like bucket and jar

### ISSUE THREAD

**Issue by whcpumpkin** [StanfordVL/iGibson#337]
Dear authors,
      When I performed behavior-100 tasks `cleaning_a_car` and `bottling_fruit` where I need to place something into a `bucket` or a `jar`, I found that there is no `inside` supporting_surfaces in `bucket` or `jar` so that `place_inside` always fails.
      Here is my code to conduct `place_inside`:
      `obj_in_hand.states[igibson.object_states.inside.Inside]._set_value(target_obj,True)`

I checked the code that loads the supporting_surfaces. It shows that supporting_surfaces is loaded by a `height_maps_per_link `file. I found that `bucket`and ` jar` do not have this file. But I checked other object like `fridge` , they have this file and have `inside` supporting_surfaces. 
    Is it my dataset that is missing? Can these two behavior tasks be performed on iGibson?

**Comment by ChengshuLi** [comment]
Hi @whcpumpkin ,

Your dataset is correct. For smaller objects like `bucket` and `jar`, we indeed do not have supporting surface annotations. 

One thing you can try is to do is to use obj.states[Inside].set_value(target_obj, True, use_ray_casting_method=True):
https://github.com/StanfordVL/iGibson/blob/7d9598278b95ec1039e1f4366c66b45346521e44/igibson/object_states/inside.py#L21C44-L21C66

This ray casting based method doesn't require supporting surface annotations and can sometimes succeed to sample. Let me know if you have any additional questions.
