### ISSUE TITLE
citation in BEHAVIOR DATA BUNDLE END USER LICENSE AGREEMENT

### ISSUE THREAD

**Issue by yihe-61wu** [StanfordVL/iGibson#342]
I just noticed that the citation and url in the [BEHAVIOR DATA BUNDLE END USER LICENSE AGREEMENT](https://drive.google.com/file/d/1FS57eF4RIaIJ382rrHJ8cVkbWCR345zw/view) does not reflect the up-to-date materials.

I'm gratefully using the software and the dateset for academic research only. Even without the agreement, I would cite your works. Nonetheless, given there is an agreement, and I signed it, I would appreciate it if you can provide an updated official guidelines on how to cite your software and dataset properly.

**Comment by cgokmen** [comment]
Hi,

You can use the below citation, which is also included on the README:

```
@inproceedings{li2022igibson,
  title = 	 {iGibson 2.0: Object-Centric Simulation for Robot Learning of Everyday Household Tasks},
  author =       {Li, Chengshu and Xia, Fei and Mart\'in-Mart\'in, Roberto and Lingelbach, Michael and Srivastava, Sanjana and Shen, Bokui and Vainio, Kent Elliott and Gokmen, Cem and Dharan, Gokul and Jain, Tanish and Kurenkov, Andrey and Liu, Karen and Gweon, Hyowon and Wu, Jiajun and Fei-Fei, Li and Savarese, Silvio},
  booktitle = 	 {Proceedings of the 5th Conference on Robot Learning},
  pages = 	 {455--465},
  year = 	 {2022},
  editor = 	 {Faust, Aleksandra and Hsu, David and Neumann, Gerhard},
  volume = 	 {164},
  series = 	 {Proceedings of Machine Learning Research},
  month = 	 {08--11 Nov},
  publisher =    {PMLR},
  pdf = 	 {https://proceedings.mlr.press/v164/li22b/li22b.pdf},
  url = 	 {https://proceedings.mlr.press/v164/li22b.html},
} 
```

Thanks!
