### ISSUE TITLE
Unable to pass tests with official docker containers(igibson/igibson:lates，igibson/igibson-vnc:v2.0.6)

### ISSUE THREAD

**Issue by chenyinlin1** [StanfordVL/iGibson#344]
To whom it may concern.
I installed the officially released docker container on my own Linux server. And tested it according to the iGibson documentation([(https://stanfordvl.github.io/iGibson/quickstart.html)]). But except for simple commands like import igibson, there are other commands involving the GUI.
Currently the container can be accessed and the gpu detected as follows：
![image](https://github.com/StanfordVL/iGibson/assets/148037200/baeb1d9d-60df-4dce-9aa9-fbe8a4834598)
But when I run the command: python -m igibson.examples.environments.env_nonint_example,  the following error is reported:
![image](https://github.com/StanfordVL/iGibson/assets/148037200/890feb03-50f1-4120-a632-26e809239b4e)
Please ask how to solve this problem. Thank you very much.

**Comment by chenyinlin1** [comment]
Using the command sudo glxinfo | grep "OpenGL" , I found out that there was a problem with the nvidia driver on the server, where the driver for opengl was not downloaded.  
![image](https://github.com/StanfordVL/iGibson/assets/148037200/72f8b2f8-f143-4688-964d-45690863f4cc)
Re-download the driver files and install them, don't bring "-no-opengl-files" in the command, so that only the driver files will be installed, not the OpenGL files. 
![image](https://github.com/StanfordVL/iGibson/assets/148037200/c03b203c-319a-4d66-a9d1-3e34085c2e4f)
Rerun the command "sudo glxinfo | grep "OpenGL"" and found that opengl supports 4.6

**Comment by chenyinlin1** [comment]
Although the opengl version issue was resolved, the iGibson GUI still cannot be displayed.
Follow the igibson instructions documentation to open the docker container:
docker run --env="DISPLAY" --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" --env="QT_X11_NO_MITSHM=1" --gpus all -ti --rm igibson/igibson:latest
Run the command and the following error is reported:
![image](https://github.com/StanfordVL/iGibson/assets/148037200/f071051a-7e6b-47c1-bdd9-61e31fc92141)

**Comment by ChengshuLi** [comment]
Is it a headless server (i.e. the server isn't connected to a display monitor)? If so, this behavior is expected. You can set `mode="headless"`.
