### ISSUE TITLE
Environment visualization?

### ISSUE THREAD

**Issue by Caselles** [StanfordVL/iGibson#35]
Hello, 

I'm having trouble manipulating the PyBullet window representing the simulation.

In this example, I use the Fetch robot in the interactive version of the Placida environment.

![image](https://user-images.githubusercontent.com/19774802/79850919-e199c080-83c4-11ea-9b7c-281a774d32e3.png)

I can zoom on the environment by scrolling, but I did not find any way to move around in this window. Plus, I saw that pressing "G" will show the environment without the additional tabs. 

Can you please indicate what are the relevant commands for this PyBullet window? I would like to move around in the environment freely, in order to visualize it.

Thanks.

**Comment by ChengshuLi** [comment]
Thank you for your question. Here are some useful ways to control the pybullet GUI window.

**Comment by Caselles** [comment]
Great, thank you so much !

Closing this issue.
