### ISSUE TITLE
auxiliary_sensor_dim missing from NavigateEnv

### ISSUE THREAD

**Issue by nstepp** [StanfordVL/iGibson#36]
I have been using `NavigateEnv` from locomotor_env.py, and in the recent version (installed via pip), that environment appears to be missing `auxiliary_sensor_dim`, which is still referenced here:
https://github.com/StanfordVL/iGibson/blob/4a283c8cae12b096c2f324fdddf92e6841a06e09/gibson2/envs/locomotor_env.py#L114

Is that environment deprecated or otherwise not recommended?

**Comment by ChengshuLi** [comment]
Thank you for your question. This part of the code is legacy code and has been removed in this PR: #37

**Comment by nstepp** [comment]
Thank you, I suspected something like that.
