### ISSUE TITLE
agent.reset() not called between subsequent episodes in sim2real challenge

### ISSUE THREAD

**Issue by karkuspeter** [StanfordVL/iGibson#38]
Hi, 

One would expect agent.reset() to be called in this loop:
https://github.com/StanfordVL/iGibson/blob/3453531543e7afa9e4e375dcb16e3e151c72d09d/gibson2/envs/challenge.py#L22-L32

Is it missing by mistake?

**Comment by ChengshuLi** [comment]
Thank you for pointing this out. We have added `agent.reset()` in this comment c96cef9.

This will be especially useful for recurrent policies because you would need to reset the hidden state in `agent.reset()`. 

Feel free to re-open this issue if you have any other questions.
