### ISSUE TITLE
IndexError in ShapeNet object load

### ISSUE THREAD

**Issue by ndstepp** [StanfordVL/iGibson#42]
This seems like a shapenet data issue, but either way there is a problem at the following line when loading shapenet objects:

https://github.com/StanfordVL/iGibson/blob/ec170937e585480b5b9af183c314c16c78507b9d/gibson2/core/render/mesh_renderer/mesh_renderer_cpu.py#L477

The issue is that there is a shape with empty material_ids (as well as empty indices). For instance, I am testing with

```
>>> obj_path = 'ShapeNetCore.v2/02828884/bc6914d649379349ab3be97afdba4e8d/models/model_normalized.obj'
>>> reader = tinyobjloader.ObjReader()
>>> reader.ParseFromFile(obj_path)
>>> shapes = reader.GetShapes()
>>> [ len(shape.mesh.material_ids) for shape in shapes ]
[120, 6908, 116, 124, 124, 24, 24, 240, 24, 24, 24, 932, 8, 16, 16, 16, 16, 16, 20, 16, 0]
```
When the referenced code gets to the last shape in the list, it encounters the error.

**Comment by fxia22** [comment]
Yes, this is indeed a shapeNet data issue. One way to go around it is to clean up shapeNet objects using blender. (import into blender, and export it into an obj file). We encourage you to use the objects in ig_dataset or follow the guide here to convert objects into iG-compatible formats https://github.com/StanfordVL/iGibson/tree/master/igibson/utils/data_utils/ext_object
