### ISSUE TITLE
Is the complexity of the room mesh file (obj file) affect the speed of iGibson?

### ISSUE THREAD

**Issue by WSPeng** [StanfordVL/iGibson#43]
Room scenes in Gibson dataset have ~300k triangle faces. I have a 3d reconstructed with 10 times more faces, is the speed of iGibson will be slowed?

**Comment by roberto-martinmartin** [comment]
Hi! Yes, the performance will be affected by the number of triangles. Especially the loading time will increase. However, for a single mesh, it would still be fast.
