### ISSUE TITLE
Matterport and Stanford 2D3DS Datasets

### ISSUE THREAD

**Issue by DavidWatkins** [StanfordVL/iGibson#45]
The original GibsonEnv codebase worked with Matterport and Stanford 2D3DS but this newer version of the simulator requires a floors.txt for the environments. Is there a way to generate it or does your team have a copy of the required files?

**Comment by roberto-martinmartin** [comment]
Sorry for the delay! They were missing from our previous version of the dataset. They should all be there in the latest version.
If you fill out the [form](https://docs.google.com/forms/d/e/1FAIpQLScWlx5Z1DM1M-wTSXaa6zV8lTFkPmTHW1LqMsoCBDWsTDjBkQ/viewform) and click submit, you should be able to download 2d3ds_for_igibson.zip with the missing floors.txt. Let us know if this works for you and feel free to reopen if you have any other problems!

**Comment by elhamAm** [comment]
This problem still exits for the Matterport dataset. Do you have a new link for the Matterport dataset where the floor_heights.txt exists?

**Comment by ChengshuLi** [comment]
@DavidWatkins 

We have updated our dataset and documentation. Could you follow this new documentation and try again? Thanks!
http://svl.stanford.edu/igibson/docs/dataset.html
