### ISSUE TITLE
Is it possible to get a segmentation mask of interactive objects in the scene?

### ISSUE THREAD

**Issue by Caselles** [StanfordVL/iGibson#47]
Hello, 

I am looking to modify this script: [examples/demo/env_interactive_example.py](https://github.com/StanfordVL/iGibson/blob/master/examples/demo/env_interactive_example.py) in order to get a segmentation mask of interactive objects (like chairs, sofa, etc) as observation (on top of the RGB observation).

**Is that possible?** What I would like is having the RGB robot view and also a segmentation mask robot view of all the interactive objects that the robot can see in his current field of view.

What I've been trying to do, unsuccessfully:

I've tried adding 'seg' as output in the config file ([examples/configs/turtlebot_interactive_demo.yaml](https://github.com/StanfordVL/iGibson/blob/master/examples/configs/turtlebot_interactive_demo.yaml)) but this is giving me an error: 

`File "[...]/.local/lib/python3.6/site-packages/gibson2/envs/locomotor_env.py", line 323, in get_seg
    if self.num_object_classes is not None:
AttributeError: 'NavigateEnv' object has no attribute 'num_object_classes'`

**Comment by Caselles** [comment]
I found more information on your paper and it does seem possible. 

I would like to reproduce exactly what you have in this Figure from your paper: 

![lll](https://user-images.githubusercontent.com/19774802/92995298-95c9ee00-f502-11ea-80b4-6b1c3f5ef75d.png)

Can you please help me out?

**Comment by roberto-martinmartin** [comment]
Duplicated with issue #63
