### ISSUE TITLE
Generating Top-down Semantic Map

### ISSUE THREAD

**Issue by shahishikas** [StanfordVL/iGibson#52]
Hello, is there a way to get a top-down semantic map of an environment? I'm interested in a map similar to the one below (from the Dataset section of the Docs), but with objects colored semantically.

![top-down-map](https://user-images.githubusercontent.com/32052298/95131659-4ba7e700-0713-11eb-8f14-c7eb24046958.PNG)

**Comment by yashkant** [comment]
Hi, I would like to know if this has been possible yet?

**Comment by ChengshuLi** [comment]
This script should do the trick. 

```
import cv2
import numpy as np

from igibson.scenes.igibson_indoor_scene import InteractiveIndoorScene
from igibson.simulator import Simulator


def main():
    s = Simulator(mode="headless", image_width=512, image_height=512, device_idx=0)
    scene = InteractiveIndoorScene(
        "Rs_int", texture_randomization=False, object_randomization=False, not_load_object_categories=["ceilings"]
    )
    s.import_ig_scene(scene)
    camera_pose = np.array([0, 0, 8.0])
    view_direction = np.array([0, 0, -1.0])
    s.renderer.set_camera(camera_pose, camera_pose + view_direction, [0, 1, 0])
    seg = s.renderer.render(modes=("seg"))[0]
    seg = (seg[:, :, 0] * MAX_CLASS_COUNT).astype(np.int)
    cv2.imwrite("test.png", seg)


if __name__ == "__main__":
    main()
```


Please feel free to re-open the issue if you have further questions.

**Comment by mjlbach** [comment]
I slightly edited eric's example above, and have included it in the next (not yet public) release of iGibson
