### ISSUE TITLE
GLSL 1.5.0 is not supported

### ISSUE THREAD

**Issue by sanjeevkoppal** [StanfordVL/iGibson#62]
Hi,

I followed the instructions for Gibson2 installation. When I run the demo code test:

I get this error:
GLSL 1.5.0 is not supported. Supported versions are ....

I did retry the installation with USE_GLAD set to FALSE in CMakeLists, but this resulted in the installation crashing.

Any ideas on the next steps I can take?

**Comment by fxia22** [comment]
Can you provide a bit more information about your platform? (os, nvidia driver version, etc)

Can you also show the output of `glxinfo`? Thanks!

**Comment by fxia22** [comment]
Judging from a few posts I read online a potential solution would be to add environment variable
`MESA_GL_VERSION_OVERRIDE=3.2` or `MESA_GL_VERSION_OVERRIDE=3.3`, not sure what is the intuition behind it.

source:
https://github.com/OpenHantek/openhantek/pull/319
https://discourse.slicer.org/t/error-glsl-1-50-is-not-supported/10083

**Comment by sanjeevkoppal** [comment]
Hi. 

I  am on Linux, specifically  a Red Hat Enterprise Server. 
I am using an NVIDIA GeForce GPU with 440.64  version driver  and cuda version 10.2 (those numbers from nvidia-smi)
When I  do ldcongif -p | grep EGL I can see 
![image](https://user-images.githubusercontent.com/20955501/107548078-3862c780-6b9c-11eb-8a53-8d469ee97ec7.png)

When I run glxinfo, it gives an unknown command error.  Would you happen to know where the command is located?

**Comment by fxia22** [comment]
glxinfo is in `mesa-utils` in ubuntu, https://packages.ubuntu.com/search?keywords=mesa-utils

I am not sure where it is on redhat. 

judging from your `ldconfig` it looks fine because you have libEGL_nvidia installed.

**Comment by sanjeevkoppal** [comment]
Do you know where I could make that change?

________________________________

**Comment by sanjeevkoppal** [comment]
> 
> 
> Judging from a few posts I read online a potential solution would be to add environment variable
> `MESA_GL_VERSION_OVERRIDE=3.2` or `MESA_GL_VERSION_OVERRIDE=3.3`, not sure what is the intuition behind it.
> 
> source:
> [OpenHantek/openhantek#319](https://github.com/OpenHantek/openhantek/pull/319)
> https://discourse.slicer.org/t/error-glsl-1-50-is-not-supported/10083

Do you know where I would edit this?

**Comment by sanjeevkoppal** [comment]
I just want to say that I ran the following on the Linux command line:
export MESA_GL_VERSION_OVERRIDE=3.3

Now the error does not show up. For a split second I can see the environment, but then it seg faults.

**Comment by ChengshuLi** [comment]
Which example code are you trying to run?

**Comment by fxia22** [comment]
I guess it should not be trying to use openGL from mesa in the first place. Can you check the output of `glxinfo`, that would be the most informative. Other debug guides on this issue can be found in http://svl.stanford.edu/igibson/docs/issues.html

**Comment by sanjeevkoppal** [comment]
I tried both env_example and demo_static. Here is the output from demo_static:
![Uploading image.png…]()

**Comment by fxia22** [comment]
Ok, this is very helpful, it is showing you are using mesa as openGL renderer, but it should be using nvidia openGL, otherwise you are not using the GPU. It would be good to figure out why nvidia opengl is not used.

Are you operating locally or trying to connect over ssh?

**Comment by sanjeevkoppal** [comment]
I am operating over an interactive desktop run by TurboVNC (setup by the server management). I start this session on a GPU.

I understood what you said about using nvidia openGL. I am not sure about how to set that up, but I will investigate.

**Comment by sanjeevkoppal** [comment]
Been investigating, but no luck. You can see from my previous posts that both Mesa and Nvidia openGL are installed, and yet I cannot get it to point only to the Nvidia open gl. Any suggestions?

**Comment by sanjeevkoppal** [comment]
Also, glxinfo is showing no command found.

**Comment by sanjeevkoppal** [comment]
Folks, believe it or not, it started working. I changed multiple things at once, so I am not sure what it was:
1. Added an ubuntu linux container module
2. Increased GPU memory (my bet is on this)
3. So far the static has worked.
Thanks for your assistance.
![image](https://user-images.githubusercontent.com/20955501/107576848-b6849580-6bbf-11eb-847f-cd1522ead581.png)
