### ISSUE TITLE
Where to access person meshes dataset? It seems not available in the official documentation.

### ISSUE THREAD

**Issue by mustang66ytz** [StanfordVL/iGibson#72]

**Comment by ChengshuLi** [comment]
@fxia22 Would you mind putting the person meshes in the assets?

**Comment by fxia22** [comment]
added, you can run `wget https://storage.googleapis.com/gibson_scenes/assets_igibson.tar.gz` to update the assets.

Note that the person meshes are also included in the data from the cvpr challenge repo, which you can download here: https://github.com/StanfordVL/iGibsonChallenge2021/blob/master/download.sh

**Comment by mustang66ytz** [comment]
I wander is there any specific scene instance or example with pedestrians moving around following orca rules with simulator running simultaneously?

**Comment by ChengshuLi** [comment]
Hi, are you trying to participate in the [iGibson Challenge 2021](http://svl.stanford.edu/igibson/challenge.html)? If so, you can follow our [started code](https://github.com/StanfordVL/iGibsonChallenge2021). 
If not, I can point you to the [social nav task](https://github.com/StanfordVL/iGibson/blob/cvpr21_challenge/gibson2/tasks/social_nav_random_task.py) that incorporates orca and the corresponding [config file](https://github.com/StanfordVL/iGibson/blob/cvpr21_challenge/gibson2/examples/configs/locobot_social_nav.yaml). 

You can try
```
cd gibson2/envs
python igibson_env.py --config ../../examples/configs/locobot_social_nav.yaml --mode gui
```

**Comment by mustang66ytz** [comment]
Cool! That is awesome!

**Comment by ChengshuLi** [comment]
Feel free to re-open the issue if you have further questions!
