### ISSUE TITLE
Object Demo doesn't show textures

### ISSUE THREAD

**Issue by yashkant** [StanfordVL/iGibson#73]
Hi,

Thanks for the code! 

I ran the [objects demo](http://svl.stanford.edu/igibson/docs/objects.html#examples) from this [file](https://github.com/StanfordVL/iGibson/blob/master/gibson2/examples/demo/object_example.py), but I do not see the object textures being loaded for articulate objects, see the image below. 

What might have gone wrong? 

![Screenshot from 2021-04-02 20-26-57](https://user-images.githubusercontent.com/17530895/113463054-d8e1a500-93f1-11eb-8de0-6d558b844428.png)

**Comment by roberto-martinmartin** [comment]
Hi,

You are visualizing with pybullet viewer. Try iGibsons viewer to see the result of iGibson rendering. Let us know if that works.

**Comment by yashkant** [comment]
Thanks for the quick reply and the suggestion, I'll try this and would reopen if I am unable to figure this out.

**Comment by fxia22** [comment]
Hi @yashkant , we just updated the assets folder, and if you delete the `gibson2/data/assets` folder and run `python -m gibson2.utils.assets_utils --download_assets` again, you should be able to get these models with textures.
