### ISSUE TITLE
Cannot download the dataset from Gibson Database of 3D Spaces

### ISSUE THREAD

**Issue by jjanixe** [StanfordVL/iGibson#79]
Hi @fxia22 and @ChengshuLi,
I tried to download the Gibson2 Room Dataset from https://docs.google.com/forms/d/e/1FAIpQLScWlx5Z1DM1M-wTSXaa6zV8lTFkPmTHW1LqMsoCBDWsTDjBkQ/viewform,
and I couldn't access the cloud storage because of the following issue.

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>UserProjectAccountProblem</Code>
<Message>User project billing account not in good standing.</Message>
<Details>The billing account for the owning project is disabled in state absent</Details>
</Error>

Could you please check if the payment was properly made?

**Comment by fxia22** [comment]
Will fix this asap, to understand more, which `tar.gz` file are you trying to download?

**Comment by jjanixe** [comment]
Thanks for the quick reply!
I was trying to download
All scenes, 572 scenes (108GB): gibson_v2_all.tar.gz  to use with iGibson(2020), 
Gibson Standard Navigation Benchmark, 
and Dataset Splits.

**Comment by fxia22** [comment]
Ok, sure, I will use another cloud bucket. Please give us some time to re-upload the data. thanks!

**Comment by fxia22** [comment]
@jjanixe the new links are up, while the upload will finish in the next couple of hours.

**Comment by jjanixe** [comment]
Thank you :) I'll close the issue if the download succeeds from the new links.

**Comment by jjanixe** [comment]
Sorry, but I just found out that the same issue occurred for the links provided for Gibson Standard Navigation Benchmark and Dataset Splits still do not work.
Could you please check if the correct links were uploaded?

**Comment by fxia22** [comment]
you can use https://storage.googleapis.com/gibson_scenes/splits.tar.gz

**Comment by fxia22** [comment]
The splits files are uploaded to https://storage.googleapis.com/gibson_scenes/splits.tar.gz while we are trying to recover the scenario files.

**Comment by fxia22** [comment]
@jjanixe updated, pls try again, thx!

**Comment by aqiu2018** [comment]
@fxia22 hi, I'am facing the same problem,  how can I fix it? 

<Error>
<Code>UserProjectAccountProblem</Code>
<Message>User project billing account not in good standing.</Message>
<Details>The billing account for the owning project is disabled in state absent</Details>
</Error>

**Comment by fxia22** [comment]
@aqiu2018 we are in the process of switching billing accounts and will fix it soon.

**Comment by fxia22** [comment]
@aqiu2018 access restored, let us know if you still have issues.
