### ISSUE TITLE
3D occupancy grid or octomap of the simulated environment

### ISSUE THREAD

**Issue by kevin-thankyou-lin** [StanfordVL/iGibson#82]
Hi! Is there a way to create a 3D obstacle map that's not through sensor data? 

I see that the trav_map in `indoor_scene.py` uses a png image to generate a 2D traversability map. If there are no 3D traversibility maps, would you have any advice on how to generate one?

**Comment by fxia22** [comment]
Hi @kevin-thankyou-lin , there are two ways of getting the occupancy grid, (depending on how fast you need it), detailed here: https://github.com/StanfordVL/iGibson/issues/67

**Comment by kevin-thankyou-lin** [comment]
Perfect, thank you!
