### ISSUE TITLE
camera artefacts

### ISSUE THREAD

**Issue by ocatal** [StanfordVL/iGibson#84]
I am currently trying out a setup similar to the turtlebot demo (http://svl.stanford.edu/igibson/docs/simulators.html).

However, I keep getting garbage rgb images when running the simulator on a remote docker instance. I am basing myself of the igibson containers provided. And have tried running it on various different hosts and different gpu's.

Does anybody know what is causing this issue?

<img width="576" alt="image" src="https://user-images.githubusercontent.com/30925281/116395636-a6766c80-a824-11eb-850e-0145c27d3f37.png">

**Comment by fxia22** [comment]
The rendered images are by default 4-channel (r,g,b,a), and looks like you are reshaping them into 3 channels, which causes the artifacts.

If you only take the first 3 channels it should look fine.
