### ISSUE TITLE
how does nav_env.test_valid_position() work?

### ISSUE THREAD

**Issue by yimengli46** [StanfordVL/iGibson#87]
I am trying to densely render observations at multiple free positions of the environment.
Sometimes when return value of `nav_env.test_valid_position()` is True, the observation is totally black, indicating current position is not free.

I also observed that if we use floor_trav_0.png as an occupancy map of an interactive scene, some furniture like bed is also traversable.

So how to know if the position is free?

**Comment by yimengli46** [comment]
And I got some very different rendering results.
This one is correct,
![21_rgb](https://user-images.githubusercontent.com/14865800/117501459-120ab900-af4c-11eb-9c18-84d514d7231b.png)
These two are weird. It seems to me there is larger environment outside of the scene.
![5_rgb](https://user-images.githubusercontent.com/14865800/117501537-2c449700-af4c-11eb-8ea3-a04464c779c0.png)
![6_rgb](https://user-images.githubusercontent.com/14865800/117501557-35cdff00-af4c-11eb-9611-ff2028aa445d.png)

I wonder why.

**Comment by sycz00** [comment]
Hey, 

the thing with the larger environment happens to me as well. I use "Benevolence_1_int" and outside the doors looks similarly blurry as in your picture.

Sorry for just a comment and no answer :(

**Comment by yimengli46** [comment]
I think I figured it out. 
The trav_map_resolution is 0.01 rather than 0.1 as mentioned in the config file.

Using the trav_map as reference to sample the observations would work.
I
