### ISSUE TITLE
Draw goal position on Occupancy grid map

### ISSUE THREAD

**Issue by sycz00** [StanfordVL/iGibson#88]
Hey all

I'd like to do a navigation task for which the agent only sees the occupancy grid map. Furthermore, the goal position should be drawn on the map. My question is: is that possible with some function ? 
I saw that @fxia22  in his paper ReLMoGen did something similar but the code has sadly not been released.

Another thing Iam not certain about: is the traverseability map created realistically ? Such that one could apply a similar concept to real-world tasks ?

Thank you for any help or hints :)

**Comment by fxia22** [comment]
@sycz00 sorry for the delay. The functionality of drawing a goal on the occupancy grid is not in this repository but I guess you can modify this part of the code to add it: https://github.com/StanfordVL/iGibson/blob/master/gibson2/sensors/scan_sensor.py#L45-L111

We will also be releasing ReLMoGen code in a few weeks so you will find the functionality there. I will keep you posted.
