### ISSUE TITLE
is there anyway that I can use to randomize the lightning?

### ISSUE THREAD

**Issue by nanlliu** [StanfordVL/iGibson#90]
much appreciated!

i found it in the render's setting, but it doesn't seem to change the lightning effects no matter what i did to the self.lightcolor and self.lightpos.

**Comment by fxia22** [comment]
Hi @nanlliu , the lightpos your are referring to is for casting shadows, if you want to randomize light, you can change the filename passed to here: https://github.com/StanfordVL/iGibson/blob/master/gibson2/render/mesh_renderer/mesh_renderer_settings.py#L13-L14

We provide a set of light probes in `ig_dataset/scenes/background`, but you can also download more environment textures from the internet to serve as light probes.

**Comment by nanlliu** [comment]
thank you so much!
